const jointMapping44 = {
  0: 'pelvis',
  1: 'leftHip',
  2: 'rightHip',
  3: 'spine1',
  4: 'leftKnee',
  5: 'rightKnee',
  6: 'spine2',
  7: 'leftAnkle',
  8: 'rightAnkle',
  9: 'spine3',
  10: 'leftFoot',
  11: 'rightFoot',
  12: 'neck',
  13: 'leftShoulder',
  14: 'rightShoulder',
  15: 'headTop',
  16: 'leftUpperArm',
  17: 'rightUpperArm',
  18: 'leftElbow',
  19: 'rightElbow',
  20: 'leftWrist',
  21: 'rightWrist',
  22: 'leftHand',
  23: 'rightHand',
  24: 'nose',
  25: 'leftEye',
  26: 'rightEye',
  27: 'leftEar',
  28: 'rightEar',
  29: 'chin',
  30: 'leftBigToe',
  31: 'leftSmallToe',
  32: 'leftHeel',
  33: 'rightBigToe',
  34: 'rightSmallToe',
  35: 'rightHeel',
  36: 'leftThumb',
  37: 'leftIndex',
  38: 'leftMiddle',
  39: 'rightThumb',
  40: 'rightIndex',
  41: 'rightMiddle',
  42: 'sternum',        // optional torso landmark
  43: 'jaw'             // optional head landmark
};

export default jointMapping44;
